services:
  - type: web
    name: laravel-api
    env: docker
    plan: starter
    region: ohio
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DATABASE_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DATABASE_NAME
        fromDatabase:
          name: laravel-db
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: laravel-api
          property: url

databases:
  - name: laravel-db
    plan: starter
    region: ohio
