services:
  - type: web
    name: laravel-api
    env: docker
    plan: starter
    region: ohio
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: laravel-api
          property: url

databases:
  - name: laravel-db
    plan: starter
    region: ohio
    ipAllowList: [] # Allow all connections
